# Generated by Django 3.1.3 on 2021-02-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarydetail',
            name='detail',
        ),
        migrations.AddField(
            model_name='diarydetail',
            name='img',
            field=models.ImageField(default='None', upload_to=''),
        ),
    ]
