# Generated by Django 3.1.3 on 2021-02-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20210221_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarydetail',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
