# Generated by Django 3.1.3 on 2021-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_diarydetail_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarydetail',
            name='img',
            field=models.ImageField(default='None', upload_to='images/'),
        ),
    ]
